### ISSUE TITLE
Reads naming

### ISSUE THREAD

**Issue by OlgaVT** [itmat/rum#189]
Hi,
I have tried RUM2 for RNA-Seq data, and in the output file all reads turned out to be renamed to "seq.1", "seq.2" etc. Is it possible to leave the names as they were in the original input files?
Thank you!

**Comment by greggrant** [comment]
Hi sorry for the delay getting back to you.
There is an option --perserve-names should achieve what you want.
Please let us know if there's anything else we can help with.
Thank you, Greg

**Comment by OlgaVT** [comment]
Thank you! I will try it.
